name: Release
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'
jobs:
  build:
      runs-on: macos-latest
      environment: production
      steps:
          - uses: actions/checkout@v2
          - name: Clean DerivedData and CocoaPods cache
            run: |
              rm -rf ~/Library/Developer/Xcode/DerivedData
              pod cache clean --all
              pod deintegrate
              pod install
        - name: Validate Podspec (Local)
          run: pod lib lint --allow-warnings --verbose
        - name: Publish to CocoaPod register
          env:
              COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          run: |
              pod trunk push AlbyWidget.podspec --allow-warnings --verbose