name: Release

on:
  push:
    # Pattern matched against refs/tags (runs on any tag push)
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to CocoaPods Trunk
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push AlbyWidget.podspec --allow-warnings --verbose
